# -*- coding: utf-8 -*-
"""Café Orders & Inventory Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12zPkQ1RySkUQ_cXOIh3onL47Yg9CdoYo

## **Arjumand Afreen Tabinda**
##**Roll No:-411210**

#**Café Orders & Inventory Tracker Assignment**:-
###**Goal:**
####**Create a Python program to manage a small café’s daily orders using lists, dictionaries,**
#### **and for loops only**
"""

## Café Orders and Inventory Tracker Assignment:-


# Given Data is:
menu = {
   "tea": 120,
   "coffee": 200,
   "sandwich": 450,
   "cookie": 150,
   "cake_slice": 320
}

inventory = {
   "tea": 40,
   "coffee": 35,
   "sandwich": 20,
   "cookie": 50,
   "cake_slice": 25
}


orders = [
   {"tea": 2, "cookie": 1},
   {"coffee": 1, "sandwich": 2},
   {"tea": 3, "cake_slice": 1},
   {"coffee": 2, "cookie": 2, "sandwich": 1},
   {"tea": 1},
   {"coffee": 1, "cake_slice": 2}
]

# Task 1: Validate & Clean Orders

processed_orders = []

for order in orders:
   cleaned = {}
   for item in order:
       if item in menu:
           if order[item] <= inventory[item]:
               cleaned[item] = order[item]
           else:
               cleaned[item] = inventory[item]
       # invalid items ignored
   processed_orders.append(cleaned)



# Task 2: Calculate Bill for Each Order:-


order_totals = []

for order in processed_orders:
   total = 0
   for item in order:
       total += order[item] * menu[item]
   order_totals.append(total)

# Task 3: Update Inventory (after each order):-


for order in processed_orders:
   for item in order:
       inventory[item] -= order[item]



# Task 4: Day Summary



# 4a. Total Revenue

total_revenue = sum(order_totals)


# 4b. Items Sold Summary

items_sold = {"tea": 0, "coffee": 0, "sandwich": 0, "cookie": 0, "cake_slice": 0}


for order in processed_orders:
   for item in order:
       items_sold[item] += order[item]


# 4c. Top Selling Item

top_selling_item = ""
highest_qty = 0
for item in items_sold:
   if items_sold[item] > highest_qty:
       highest_qty = items_sold[item]
       top_selling_item = item


# Task 5: Low Stock Report


low_stock = []

for item in inventory:
   if inventory[item] <= 5:
       low_stock.append(item)




# Task 6:  Apply Simple Discount



order_totals_with_discount = []

for total in order_totals:
   if total > 1000:
       discount = total * 0.10
       total = total - discount
   order_totals_with_discount.append(round(total))

total_revenue_with_discount = sum(order_totals_with_discount)


# Task 7:  Loyalty Points

order_points = []
total_points = 0

for total in order_totals_with_discount:
   points = total // 100
   order_points.append(points)
   total_points += points


# FOR PRINT RESULTS SECTION:-

print("\n== PROCESSED ORDERS ==")

print(processed_orders)

print("\n== ORDER TOTALS ==")

print(order_totals)

print("\n== INVENTORY AFTER SALES ==")

print(inventory)

print("\n== ITEMS SOLD SUMMARY ==")

print(items_sold)

print("Top Selling Item:", top_selling_item)

print("\n== LOW STOCK ITEMS (<=5) ==")

print(low_stock)

print("\n== ORDER TOTALS WITH DISCOUNT ==")

print(order_totals_with_discount)
print("Total Revenue After Discount:", total_revenue_with_discount)

print("\n== LOYALTY POINTS  ==")

print(order_points)
print("Total Loyalty Points Today:", total_points)

"""
#**Details About Project:-**
####This project manages a café’s orders using only lists, dictionaries, and for-loops,
####just like the PDF required. I used dictionaries to store menu, inventory, and each order, used lists to store all orders, totals, low stock items, and loyalty points, used loops to validate orders, calculate bills, update stock, count items sold, apply discounts, and calculate points. This makes the project simple, clear, and fully according to the assignment instructions(requirements).
"""